### ISSUE TITLE
Optimizing Links for Chrome Audits

### ISSUE THREAD

**Issue by jcliftonmeek** [the-muda-organization/youtube-lazyload#1]
**Problem:**
Chrome DevTools Audit (Lighthouse) requires rel="noopener" or "noreferrer" for best practices. YT-Lazyload's <a> links for the play button gets dinged.

**Resolution:**
Add **ytlogo.rel** as noted below
```
        //logo link
        ytlogo.classList.add('yt-lazyload-logo');
        ytlogo.href = 'https://youtu.be/' + data_id;
        ytlogo.target = '_blank';
        **ytlogo.rel = 'noreferrer';**
```

**Comment by jakubmuda** [comment]
Added in v3.0.1
