### ISSUE TITLE
lazy-load the thumbnail also!

### ISSUE THREAD

**Issue by realdealpeel** [the-muda-organization/youtube-lazyload#2]
Hi!

Great tool here! Just one feature missing that I cannot figure out how to implement: lazy-loading the thumbnail. 

A high-res thumbnail can be fairly large and it makes sense to be able to lazy-load it in case it renders initially below the viewport.

I use echo.js to lazy-load all images on my site, but I cannot figure out how to make echo.js work with youtube-lazyload.js. Echo.js works by adding src="blank.png" instead of the actual image, and then adding data-echo="example.jpg" for the actual image.

If you or anyone has any ideas on how to make this work, please let me know! Thanks!!

Eric

**Comment by jakubmuda** [comment]
There is a big update coming soon - code made from scratch. I will take a look and make simple lazyload. I don't want to add extra librairies because I want the script to be easy to customize!

**Comment by realdealpeel** [comment]
Thanks very much, Jakub! This is my first time commenting on Github so let me know if I'm supposed to close it, or close it for me. And I'll be watching your project for your update.

**Comment by jakubmuda** [comment]
In V4 image lazyload will be done using [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). This is a modern approach and it's very simple to implement 😉 

V4 should be released by the end of the month.

**Comment by realdealpeel** [comment]
Awesome! Thanks for your work, Jakub!

**Comment by jakubmuda** [comment]
Added in v.4.0.0 😉
