### ISSUE TITLE
Bug iOS 14 or not?

### ISSUE THREAD

**Issue by hollow-frenk** [the-muda-organization/youtube-lazyload#3]
Hi, I don't know if it is normal or not but on iOS 14 the autoplay of the videos does not start and therefore you have to tap the play button twice. P.s. On desktop, all right. P.p.s. I wanted to report everything because it could be a bug. Edit, The same thing happens on android too

**Comment by jakubmuda** [comment]
> The reason that video autoplay doesn’t work is simple. The feature is deliberately disabled in both iOS and Android for mobile devices. The reason this is done is to save mobile users money. Such devices (especially mobile phones) often use data connections that charge by bandwidth. They have data limits and going over results in a fee.

https://stackoverflow.com/questions/48399390/youtube-embed-autoplay-on-mobile

https://stackoverflow.com/questions/15090782/youtube-autoplay-not-working-on-mobile-devices-with-embedded-html5-player
